name: 'Image: Klipper'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'
jobs:
  build:
    uses: ./.github/workflows/image-workflow.yaml
    with:
      app: klipper
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}